service: image-upload-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  environment:
    BUCKET_NAME: ${self:custom.bucketName}

functions:
  uploadImage:
    handler: src/handler.uploadImage
    events:
      - http:
          path: upload/{fileName}
          method: post
          cors: true
          request:
            parameters:
              paths:
                fileName: true

resources:
  Resources:
    ImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
              AllowedOrigins:
                - "*"
              MaxAge: 3000

plugins:
  - serverless-offline

custom:
  bucketName: "image-upload-service-${opt:stage, 'dev'}-bucket"
